"""Typed clients for Wit's external services."""

from wit.clients.health import ServiceHealthResult, ServiceHealthState, ServiceName
from wit.clients.jellyfin import JellyfinClient
from wit.clients.seerr import SeerrClient
from wit.clients.sonarr import (
    InvalidSonarrDefaultsError,
    InvalidSonarrRequestError,
    InvalidSonarrResponseError,
    SonarrClient,
    SonarrClientError,
    SonarrEpisode,
    SonarrEpisodeAirStatus,
    SonarrEpisodeMappingError,
    SonarrEpisodeMonitoringResult,
    SonarrLibraryDefaults,
    SonarrQualityProfile,
    SonarrRootFolder,
    SonarrSeries,
    SonarrSeriesAddResult,
    SonarrSeriesLookupResult,
    SonarrSeriesNotFoundError,
    SonarrSeriesType,
    map_episode_coordinate,
)
from wit.clients.tvmaze import (
    InvalidTvmazeRequestError,
    InvalidTvmazeResponseError,
    TvmazeClient,
    TvmazeClientError,
    TvmazeEpisode,
    TvmazeEpisodeCollection,
    TvmazeEpisodeType,
    TvmazeShow,
    TvmazeShowSearchResult,
)

__all__ = [
    "InvalidSonarrDefaultsError",
    "InvalidSonarrRequestError",
    "InvalidSonarrResponseError",
    "InvalidTvmazeRequestError",
    "InvalidTvmazeResponseError",
    "JellyfinClient",
    "SeerrClient",
    "ServiceHealthResult",
    "ServiceHealthState",
    "ServiceName",
    "SonarrClient",
    "SonarrClientError",
    "SonarrEpisode",
    "SonarrEpisodeAirStatus",
    "SonarrEpisodeMappingError",
    "SonarrEpisodeMonitoringResult",
    "SonarrLibraryDefaults",
    "SonarrQualityProfile",
    "SonarrRootFolder",
    "SonarrSeries",
    "SonarrSeriesAddResult",
    "SonarrSeriesLookupResult",
    "SonarrSeriesNotFoundError",
    "SonarrSeriesType",
    "TvmazeClient",
    "TvmazeClientError",
    "TvmazeEpisode",
    "TvmazeEpisodeCollection",
    "TvmazeEpisodeType",
    "TvmazeShow",
    "TvmazeShowSearchResult",
    "map_episode_coordinate",
]
